permissions:
  contents: read
name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
  pull_request:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'

jobs:
  phpstan:
    name: Static Analysis (PHPStan)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, json
          coverage: none

      - name: Install dependencies (if needed)
        run: |
          if [ -f composer.json ]; then
            composer install --no-interaction --prefer-dist
          fi

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --configuration=phpstan.neon.dist
